name: Deploy Streamlit App "Toxic Rephraser"

on:
  push:
    branches: [main]
    paths:
      - toxic-rephraser/**

jobs:
  deploy-toxic-rephraser:
    name: Deploy toxic-rephraser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2

      - name: Create app.yaml
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: toxic-rephraser/app.yaml.jinja
          output_file: toxic-rephraser/app.yaml
          strict: true
          variables: |
            CO_KEY=${{ secrets.COHERE_API_KEY }}
            # More environment variables go here

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: toxic-rephraser/app.yaml
          project_id: "${{ secrets.GCP_PROJECT }}"

      - name: Healthcheck
        id: curl-api
        run: curl "${{ steps.deploy.outputs.url }}/healthz"
